---
title: "HW_3"
author: "Austin Pesina"
date: "4/22/2021"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
setwd("~/Intro_to_R/")
library(tidyverse)
library(magrittr)
```


```{r data}
##READ IN CENSUS FILE
census<-read_lines('~/Intro_to_R/HW_3/data/usa_census_regions.txt',skip=1) #SKIP THE FIRST ROW
usa_census_regions<-read_fwf(census, fwf_widths(c(2, 19, 21), col_names=c('X','census_regions','state')))
## HARDEST PART IS FIGURING OUT THOSE WIDTHS
## FIRST WIDTH IS 2 FOR X CAUSE WE HAVE NUMBERS RANGING FROM 1 TO 51
## SECOND IS 19 FOR West North Central
## LAST IS 21 FOR District of Columbia
## I TRIED 20 BUT IT CUT OFF THE LAST CHARACTER



## READ IN CORN
c<-read_lines('~/Intro_to_R/HW_3/data/corn.txt',skip=1)#SKIP THE FIRST ROW
corn<-read_fwf(c,fwf_empty(c,col_names=c('obs','year','state','farmed_area_acres','yield_bushels_per_acre')))
## HERE I USED FWF_EMPTY INSTEAD OF FWF_WIDTHS 
## EMPTY IS NICE CAUSE IT'LL GUESS THE WIDTHS FOR ME




## READ IN WHEAT
w<-read_lines('~/Intro_to_R/HW_3/data/wheat.txt',skip=1)#SKIP THE FIRST ROW
wheat<-read_fwf(w,fwf_empty(w,col_names=c('obs','year','state','farmed_area_acres','yield_bushels_per_acre')))
## SAME AS CORN
## FOR MORE INFO ON read_fwf VISIT https://readr.tidyverse.org/reference/read_fwf.html
```



## Grain Yields and Unit Conversion

```{r Question 1}
acres_to_sq_yards <- function(acres) {
  acres * 4840
}
```

```{r Question 2}
# Write a function to convert yards to meters
yards_to_meters <- function(yards) {
  (yards * 36) * 0.0254
}
```

```{r Question 3}
sq_meters_to_hectares <- function(sq_meters) {
  sq_meters / 10000
}
```

```{r Question 4}
##Part 1

# Write a function to convert sq. yards to sq. meters
sq_yards_to_sq_meters <- function(sq_yards) {
  sq_yards %>%
    # Take the square root
    sqrt() %>%
    # Convert yards to meters
    yards_to_meters() %>%
    # Square it
    raise_to_power(2)
}


##Part 2

# Write a function to convert acres to hectares
acres_to_hectares <- function(acres) {
  acres %>%
    # Convert acres to sq yards
    acres_to_sq_yards() %>%
    # Convert sq yards to sq meters
    sq_yards_to_sq_meters() %>%
    # Convert sq meters to hectares
    sq_meters_to_hectares()
}


##Part 3

# reciprocal function
get_reciprocal <- function(x) {
 1/x
}

# Define a harmonic acres to hectares function
harmonic_acres_to_hectares <- function(acres) {
  acres %>% 
    # Get the reciprocal
    get_reciprocal() %>%
    # Convert acres to hectares
    acres_to_hectares() %>% 
    # Get the reciprocal again
    get_reciprocal()
}
```

```{r Question 5}
##Part 1

# Write a function to convert lb to kg
lbs_to_kgs <- function(lbs){
  lbs * 0.45359237
}

##Part 2

# Write a function to convert bushels to lbs
bushels_to_lbs <- function(bushels, crop) {
  # Define a lookup table of scale factors
  c(barley = 48, corn = 56, wheat = 60) %>%
    # Extract the value for the crop
    extract(crop) %>%
    # Multiply by the no. of bushels
    multiply_by(bushels)
}


##Part 3

# Write a function to convert bushels to kg
bushels_to_kgs <- function(bushels, crop) {
  bushels %>%
    # Convert bushels to lbs for this crop
    bushels_to_lbs(crop) %>%
    # Convert lbs to kgs
    lbs_to_kgs()
}

##Part 4

# Write a function to convert bushels/acre to kg/ha
bushels_per_acre_to_kgs_per_hectare <- function(bushels_per_acre, crop = c("barley", "corn", "wheat")) {
  # Match the crop argument
  crop <- match.arg(crop)
  bushels_per_acre %>%
    # Convert bushels to kgs for this crop
    bushels_to_kgs(crop) %>%
    # Convert harmonic acres to ha
    harmonic_ac
}
```

```{r Question 6}
##Part 1
glimpse(corn)

corn <- corn %>%
  # Add some columns
  mutate(
    # Convert farmed area from acres to ha
    farmed_area_ha = acres_to_hectares(acres),
    # Convert yield from bushels/acre to kg/ha
    yield_kg_per_ha = bushels_per_acre_to_kgs_per_hectare(
      yield,
      crop = "corn"
    )
  )

head(corn)
## Part 2

# Wrap this code into a function
fortify_with_metric_units <- function(data, crop) {
  data %>%
    mutate(
      farmed_area_ha = acres_to_hectares(acres),
      yield_kg_per_ha = bushels_per_acre_to_kgs_per_hectare(
        yield, 
        crop = crop
      )
    )
}


# Try it on the wheat dataset
wheat <- fortify_with_metric_units(wheat, crop = "wheat")
head(wheat)
```


Visualizing Grain Yields

```{r}
library(ggplot2)
```

```{r Question 1}
# Using corn, plot yield (kg/ha) vs. year
ggplot(corn, aes(x = year, y = yield_kg_per_ha)) +
  # Add a line layer, grouped by state
  geom_line(aes(group = state)) +
  # Add a smooth trend layer
  geom_smooth()

plot_yield_vs_year <- function(data){
  ggplot(data, aes(year, yield_kg_per_ha)) +
    geom_line(aes(group = state)) +
    geom_smooth()
}

```

## Visualizing Grain Yields

```{r Question 1}

```

```{r Question 2}

```

```{r Question 3}

```

```{r Question 4}

```

## Modeling Grain Yields

```{r Question 1}
#Run a GAM of yield_kg_per_ha versus smoothed year and census region, using the corn dataset.

# Run a generalized additive model of # yield vs. smoothed year and census region
gam(yield_kg_per_ha ~ s(year) + census_region, data = corn)

#Wrap the modeling code into a function, run_gam_yield_vs_year_by_region. This should take a single argument, data, with no default.

# Wrap the model code into a function
run_gam_yield_vs_year_by_region <- function(data){
  gam(yield_kg_per_ha ~ s(year) + census_region, data = data)
}


# Try it on the wheat dataset
run_gam_yield_vs_year_by_region(wheat)
```

```{r Question 2}
# Make predictions in 2050  
predict_this <- data.frame(
  year = 2050,
  census_region = census_regions
) 

# Predict the yield
pred_yield_kg_per_ha <- predict(corn_model, predict_this, type = "response")

predict_this %>%
  # Add the prediction as a column of predict_this 
  mutate(pred_yield_kg_per_ha = pred_yield_kg_per_ha)



# Wrap this prediction code into a function
predict_yields <- function(model, year) {
  predict_this <- data.frame(
    year = 2050,
    census_region = census_regions
  ) 
  pred_yield_kg_per_ha <- predict(model, predict_this, type = "response")
  predict_this %>%
    mutate(pred_yield_kg_per_ha = pred_yield_kg_per_ha)
}

# Try it on the wheat dataset
predict_yields(wheat_model, year = 2050)
```


```{r Question 3}
fortified_barley <- barley %>% 
  # Fortify with metric units
  fortify_with_metric_units() %>%
  # Fortify with census regions
  fortify_with_census_region()

# See the result
glimpse(fortified_barley)



# Plot yield vs. year by region
plot_yield_vs_year_by_region(fortified_barley)


# Run a GAM of yield vs. year by region
  run_gam_yield_vs_year_by_region()  %>% 
  # Make predictions of yields in 2050
  predict_yields(2050)
```

### Purr

## Part 1
```{r}
library(repurrrsive)
```

```{r}
data(gh_users)
names(gh_users)
map(gh_users, ~.x[["name"]])
```

```{r}
# Name gh_users with the names of the users
gh_users_named <- gh_users %>% 
    set_names(map_chr(gh_users, "name"))

# Check gh_repos structure
str(gh_repos)

# Name gh_repos with the names of the repo owner 
gh_repos_named <- gh_repos %>% 
    map_chr(~ .[[1]]$owner$login) %>% 
    set_names(gh_repos, .)




# Determine who joined github first
map_chr(gh_users, ~ .x[["created_at"]]) %>%
      set_names(map_chr(gh_users,"name")) %>%
    sort()



# Determine user versus organization
map_lgl(gh_users, ~ .x[["type"]] == "User") 



# Determine who has the most public repositories
map_int(gh_users, ~ .x[["public_repos"]]) %>%
    set_names(map_chr(gh_users, "name")) %>%
    sort()
```


## Part 2

```{r}
# Map over gh_repos to generate numeric output
map(gh_repos,
    ~map_dbl(.x, 
             ~.x[["size"]])) %>%
    # Grab the largest element
    map(~max(.x))
```



## Part 3
```{r}
# Scatter plot of public repos and followers
ggplot(data = gh_users_df, 
       aes(x = public_repos, y = followers))+
    geom_point()


# Histogram of followers        
gh_users_df %>%
    ggplot(aes(x = followers))+
        geom_histogram() 
```


```{r}
# Create a dataframe with four columns
map_df(gh_users, `[`, 
       c("login","name","followers","public_repos")) %>%
       # Plot followers by public_repos
    ggplot(., 
         aes(x = followers, y = public_repos)) + 
        # Create scatter plots
        geom_point()
```

```{r}
# Turn data into correct dataframe format
film_by_character <- tibble(filmtitle = map_chr(sw_films, "title")) %>%
    mutate(filmtitle, characters = map(sw_films, "characters")) %>%
    unnest()

# Pull out elements from sw_people
sw_characters <- map_df(sw_people, `[`, c("height","mass","name","url"))

# Join our two new objects
character_data <- inner_join(film_by_character, sw_characters, by = c("characters" = "url")) %>%
    # Make sure the columns are numbers
    mutate(height = as.numeric(height), mass = as.numeric(mass))

# Plot the heights, faceted by film title
ggplot(character_data, aes(x = height)) +
  geom_histogram(stat = "count") +
  facet_wrap(~ filmtitle)
```